const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("aideagent", {
  test: "hello",
  version: process.versions.electron,
  respondPermission: (/** @type {any} */ id, /** @type {any} */ allow) => ipcRenderer.invoke("permission:respond", { id, allow }),
  onPermissionRequest: (/** @type {any} */ cb) => ipcRenderer.on("permission:request", (_event, d) => cb(d)),
  submitQuery: (/** @type {any} */ prompt, /** @type {any} */ apiKey, /** @type {any} */ apiUrl, /** @type {any} */ model, /** @type {any} */ apiFormat, /** @type {any} */ files, /** @type {any} */ enabledSkills, /** @type {any} */ reasoning, /** @type {any} */ agentName, /** @type {any} */ kbEnabled, /** @type {any} */ planMode, /** @type {any} */ webSearchEnabled) => ipcRenderer.invoke("query:submit", { prompt, apiKey, apiUrl, model, apiFormat, files, enabledSkills, reasoning, agentName, kbEnabled, planMode, webSearchEnabled }),
  setPlanMode: (/** @type {any} */ enabled) => ipcRenderer.invoke("plan-mode:set", enabled),
  getPlanMode: () => ipcRenderer.invoke("plan-mode:get"),
  abortQuery: () => ipcRenderer.invoke("query:abort"),
  resetSession: () => ipcRenderer.invoke("session:reset"),
  listSessions: () => ipcRenderer.invoke("session:list"),
  loadSession: (/** @type {any} */ id, /** @type {any} */ opts) => ipcRenderer.invoke("session:load", id, opts),
  deleteSession: (/** @type {any} */ id) => ipcRenderer.invoke("session:delete", id),
  deleteAllSessions: () => ipcRenderer.invoke("session:delete-all"),
  deleteMessage: (/** @type {any} */ messageId) => ipcRenderer.invoke("session:delete-message", messageId),
  searchSessions: (/** @type {any} */ query, /** @type {any} */ limit) => ipcRenderer.invoke("session:search", query, limit),
  getLastSession: (/** @type {any} */ limit) => ipcRenderer.invoke("session:last", limit),
  getSessionStatus: () => ipcRenderer.invoke("session:status"),
  // Memory Store
  memoryReadUser: () => ipcRenderer.invoke("memory:read-user"),
  memoryWriteUser: (/** @type {any} */ content) => ipcRenderer.invoke("memory:write-user", content),
  memoryAppendUser: (/** @type {any} */ content) => ipcRenderer.invoke("memory:append-user", content),
  memoryReadProject: () => ipcRenderer.invoke("memory:read-project"),
  memoryWriteProject: (/** @type {any} */ content) => ipcRenderer.invoke("memory:write-project", content),
  memoryAppendProject: (/** @type {any} */ content) => ipcRenderer.invoke("memory:append-project", content),
  memorySearch: (/** @type {any} */ query) => ipcRenderer.invoke("memory:search", query),
  editMessage: (/** @type {any} */ messageId, /** @type {any} */ newContent) => ipcRenderer.invoke("session:edit-message", messageId, newContent),
  exportSessionMarkdown: (/** @type {any} */ id) => ipcRenderer.invoke("session:export-markdown", id),
  // Skills
  skillsListAll: () => ipcRenderer.invoke("skills:list-all"),
  skillsLoadOne: (/** @type {any} */ name) => ipcRenderer.invoke("skills:load-one", name),
  skillsSetStatus: (/** @type {any} */ name, /** @type {any} */ status) => ipcRenderer.invoke("skills:set-status", name, status),
  skillsDelete: (/** @type {any} */ name) => ipcRenderer.invoke("skills:delete", name),
  skillsDetectPatterns: () => ipcRenderer.invoke("skills:detect-patterns"),
  skillsCuratorRun: () => ipcRenderer.invoke("skills:curator-run"),
  skillsCuratorStatus: () => ipcRenderer.invoke("skills:curator-status"),
  skillsCuratorConfig: (/** @type {any} */ config) => ipcRenderer.invoke("skills:curator-config", config),
  skillsHealth: (/** @type {any} */ name) => ipcRenderer.invoke("skills:health", name),
  skillsSaveSkill: (/** @type {any} */ name, /** @type {any} */ meta, /** @type {any} */ body) => ipcRenderer.invoke("skills:save", name, meta, body),
  skillsSearch: (/** @type {any} */ query, /** @type {any} */ limit) => ipcRenderer.invoke("skills:search", query, limit),
  skillsReindex: () => ipcRenderer.invoke("skills:reindex"),
  // Phase 2: per-user Chinese skill-name translations (display-only cache)
  skillsTranslationsGet: () => ipcRenderer.invoke("skills:translations-get"),
  skillsTranslationsMissing: () => ipcRenderer.invoke("skills:translations-missing"),
  skillsTranslationsEnsure: (/** @type {any} */ apiConfig) => ipcRenderer.invoke("skills:translations-ensure", apiConfig),
  onTranslationsUpdated: (/** @type {any} */ cb) => ipcRenderer.on("skills:translations-updated", (_event, d) => cb(d)),
  listSkills: () => ipcRenderer.invoke("skills:list"),
  loadSkill: (/** @type {any} */ name) => ipcRenderer.invoke("skills:load", name),
  onStreamStart: (/** @type {any} */ cb) => ipcRenderer.on("stream:start", () => cb()),
  onStreamMetrics: (/** @type {any} */ cb) => ipcRenderer.on("stream:metrics", (_event, d) => cb(d)),
  onStreamChunk: (/** @type {any} */ cb) => ipcRenderer.on("stream:chunk", (_event, d) => cb(d)),
  onStreamReasoning: (/** @type {any} */ cb) => ipcRenderer.on("stream:reasoning", (_event, d) => cb(d)),
  onStreamDone: (/** @type {any} */ cb) => ipcRenderer.on("stream:done", () => cb()),
  onStreamError: (/** @type {any} */ cb) => ipcRenderer.on("stream:error", (_event, d) => cb(d)),
  onToolStart: (/** @type {any} */ cb) => ipcRenderer.on("tool:start", (_event, d) => cb(d)),
  onToolResult: (/** @type {any} */ cb) => ipcRenderer.on("tool:result", (_event, d) => cb(d)),
  onSubagentStart: (/** @type {any} */ cb) => ipcRenderer.on("subagent:start", (_event, d) => cb(d)),
  onSubagentChunk: (/** @type {any} */ cb) => ipcRenderer.on("subagent:chunk", (_event, d) => cb(d)),
  onSubagentProgress: (/** @type {any} */ cb) => ipcRenderer.on("subagent:progress", (_event, d) => cb(d)),
  onSubagentDone: (/** @type {any} */ cb) => ipcRenderer.on("subagent:done", (_event, d) => cb(d)),
  onSessionUpdate: (/** @type {any} */ cb) => ipcRenderer.on("session:update", (_event, d) => cb(d)),
  onL0Budget: (/** @type {any} */ cb) => ipcRenderer.on("l0:budget", (_event, d) => cb(d)),
  onContextUsage: (/** @type {any} */ cb) => ipcRenderer.on("context:usage", (_event, d) => cb(d)),
  onTaskClear: (/** @type {any} */ cb) => ipcRenderer.on("task:clear", () => cb()),
  onPatternsDetected: (/** @type {any} */ cb) => ipcRenderer.on("agent-skill:patterns-detected", (_event, d) => cb(d)),
  // System prompt profiles
  listPromptProfiles: () => ipcRenderer.invoke("prompt:list"),
  getDefaultPrompt: () => ipcRenderer.invoke("prompt:default"),
  savePromptProfile: (/** @type {any} */ profile) => ipcRenderer.invoke("prompt:save", profile),
  deletePromptProfile: (/** @type {any} */ profileId) => ipcRenderer.invoke("prompt:delete", profileId),
  activatePromptProfile: (/** @type {any} */ profileId) => ipcRenderer.invoke("prompt:activate", profileId),
  // MCP
  mcpList: () => ipcRenderer.invoke("mcp:list"),
  mcpConfig: () => ipcRenderer.invoke("mcp:config"),
  mcpAdd: (/** @type {any} */ name, /** @type {any} */ config) => ipcRenderer.invoke("mcp:add", { name, config }),
  mcpRemove: (/** @type {any} */ name) => ipcRenderer.invoke("mcp:remove", name),
  mcpRestart: (/** @type {any} */ name) => ipcRenderer.invoke("mcp:restart", name),
  mcpDetectLocal: () => ipcRenderer.invoke("mcp:detect-local"),
  mcpAddRemote: (/** @type {any} */ name, /** @type {any} */ url, /** @type {any} */ headers) => ipcRenderer.invoke("mcp:add-remote", { name, url, headers }),
  mcpSaveAll: () => ipcRenderer.invoke("mcp:save-all"),
  mcpQuickAddSearxng: (/** @type {any} */ url) => ipcRenderer.invoke("mcp:quick-add-searxng", url),
  mcpBuiltins: () => ipcRenderer.invoke("mcp:builtins"),
  mcpToggleBuiltin: (/** @type {any} */ name, /** @type {any} */ enabled) => ipcRenderer.invoke("mcp:toggle-builtin", { name, enabled }),
  downloadMarkdown: (/** @type {any} */ content) => ipcRenderer.invoke("dialog:download-markdown", content),
  // WeChat iLink Bridge
  wechatGetQrcode: () => ipcRenderer.invoke("wechat:get-qrcode"),
  wechatPollStatus: (/** @type {any} */ qrcodeId) => ipcRenderer.invoke("wechat:poll-status", qrcodeId),
  wechatLogin: (/** @type {any} */ creds) => ipcRenderer.invoke("wechat:login", creds),
  wechatLogout: () => ipcRenderer.invoke("wechat:logout"),
  wechatGetStatus: () => ipcRenderer.invoke("wechat:get-status"),
  onWechatBotStatus: (/** @type {any} */ cb) => ipcRenderer.on("wechat:bot-status", (_e, d) => cb(d)),
  onWechatIncoming: (/** @type {any} */ cb) => ipcRenderer.on("wechat:incoming", (_e, d) => cb(d)),
  syncApiToWechat: (/** @type {any} */ cfg) => ipcRenderer.invoke("api:sync-to-wechat", cfg),
  // AskUserQuestion
  onAskQuestion: (/** @type {any} */ cb) => ipcRenderer.on("ask:question", (_e, d) => cb(d)),
  respondQuestion: (/** @type {any} */ id, /** @type {any} */ answers) => ipcRenderer.invoke("ask:respond", { id, answers }),
  // Memory (multi-file)
  memoryListAll: () => ipcRenderer.invoke("memory:list-all"),
  memoryReadOne: (/** @type {any} */ filename) => ipcRenderer.invoke("memory:read-one", filename),
  memoryCreate: (/** @type {any} */ name, /** @type {any} */ description, /** @type {any} */ type, /** @type {any} */ content) => ipcRenderer.invoke("memory:create", { name, description, type, content }),
  memoryUpdate: (/** @type {any} */ filename, /** @type {any} */ content, /** @type {any} */ name, /** @type {any} */ description, /** @type {any} */ type) => ipcRenderer.invoke("memory:update", { filename, content, name, description, type }),
  memoryDelete: (/** @type {any} */ filename) => ipcRenderer.invoke("memory:delete", filename),
  workspaceGet: () => ipcRenderer.invoke("workspace:get"),
  workspaceSet: (/** @type {any} */ path) => ipcRenderer.invoke("workspace:set", path),
  workspacePick: () => ipcRenderer.invoke("workspace:pick"),
  workspaceNeedsFirstPick: () => ipcRenderer.invoke("workspace:needs-first-pick"),
  // Knowledge Base
  kbGetVault: () => ipcRenderer.invoke("kb:get-vault"),
  kbSetVault: (/** @type {any} */ path) => ipcRenderer.invoke("kb:set-vault", path),
  kbPickVault: () => ipcRenderer.invoke("kb:pick-vault"),
  kbConfig: () => ipcRenderer.invoke("kb:config"),
  kbSetConfig: (/** @type {any} */ cfg) => ipcRenderer.invoke("kb:set-config", cfg),
  kbScan: () => ipcRenderer.invoke("kb:scan"),
  kbStatus: () => ipcRenderer.invoke("kb:status"),
  kbSearch: (/** @type {any} */ query, /** @type {any} */ limit) => ipcRenderer.invoke("kb:search", query, limit),
  kbList: (/** @type {any} */ offset, /** @type {any} */ limit) => ipcRenderer.invoke("kb:list", offset, limit),
  kbGetNote: (/** @type {any} */ path) => ipcRenderer.invoke("kb:get-note", path),
  kbCreateNote: (/** @type {any} */ path, /** @type {any} */ content, /** @type {any} */ tags) => ipcRenderer.invoke("kb:create-note", { path, content, tags }),
  kbUpdateNote: (/** @type {any} */ path, /** @type {any} */ content) => ipcRenderer.invoke("kb:update-note", { path, content }),
  kbDeleteNote: (/** @type {any} */ path) => ipcRenderer.invoke("kb:delete-note", path),
  kbOllamaModels: () => ipcRenderer.invoke("kb:ollama-models"),

  // Update Manager
  updateCheckVersion: () => ipcRenderer.invoke("update:get-version"),
  updateCheckForUpdates: () => ipcRenderer.invoke("update:check"),
  updateInstall: () => ipcRenderer.invoke("update:install"),
  onUpdateStatus: (/** @type {any} */ cb) => ipcRenderer.on("update:status", (_e, d) => cb(d)),
  onUpdateProgress: (/** @type {any} */ cb) => ipcRenderer.on("update:progress", (_e, d) => cb(d)),

  // Encrypted API Key Storage
  saveApiKey: (/** @type {any} */ provider, /** @type {any} */ key) => ipcRenderer.invoke("api-key:save", { provider, key }),
  loadApiKey: (/** @type {any} */ provider) => ipcRenderer.invoke("api-key:load", { provider }),
  deleteApiKey: (/** @type {any} */ provider) => ipcRenderer.invoke("api-key:delete", { provider }),
  getEnvVar: (/** @type {any} */ name) => ipcRenderer.invoke("env:get", name),
});
