import { contextBridge, ipcRenderer } from "electron";

contextBridge.exposeInMainWorld("aideagent", {
  test: "hello",
  version: process.versions.electron,
  respondPermission: (id: any, allow: any) => ipcRenderer.invoke("permission:respond", { id, allow }),
  onPermissionRequest: (cb: any) => ipcRenderer.on("permission:request", (_event, d) => cb(d)),
  submitQuery: (prompt: any, apiKey: any, apiUrl: any, model: any, apiFormat: any, files: any, enabledSkills: any, reasoning: any, agentName: any, kbEnabled: any, planMode: any, webSearchEnabled: any, runtime: any, opencodeModelId: any, contextWindowOverride: any) => ipcRenderer.invoke("query:submit", { prompt, apiKey, apiUrl, model, apiFormat, files, enabledSkills, reasoning, agentName, kbEnabled, planMode, webSearchEnabled, runtime, opencodeModelId, contextWindowOverride }),
  detectOpencode: () => ipcRenderer.invoke("agent:detect-opencode"),
  listOpencodeModels: () => ipcRenderer.invoke("opencode:list-models"),
  fetchModels: (baseUrl: any, apiKey: any) => ipcRenderer.invoke("api:fetch-models", { baseUrl, apiKey }),
  openExternal: (url: any) => ipcRenderer.invoke("shell:open-external", url),
  setPlanMode: (enabled: any) => ipcRenderer.invoke("plan-mode:set", enabled),
  getPlanMode: () => ipcRenderer.invoke("plan-mode:get"),
  abortQuery: () => ipcRenderer.invoke("query:abort"),
  resetSession: () => ipcRenderer.invoke("session:reset"),
  listSessions: () => ipcRenderer.invoke("session:list"),
  loadSession: (id: any, opts: any) => ipcRenderer.invoke("session:load", id, opts),
  deleteSession: (id: any) => ipcRenderer.invoke("session:delete", id),
  deleteAllSessions: () => ipcRenderer.invoke("session:delete-all"),
  deleteMessage: (messageId: any) => ipcRenderer.invoke("session:delete-message", messageId),
  searchSessions: (query: any, limit: any) => ipcRenderer.invoke("session:search", query, limit),
  getLastSession: (limit: any) => ipcRenderer.invoke("session:last", limit),
  getSessionStatus: () => ipcRenderer.invoke("session:status"),
  getTurnProgress: (id: any) => ipcRenderer.invoke("session:turn-progress", id),
  clearTurnProgress: (id: any) => ipcRenderer.invoke("session:clear-turn-progress", id),
  replayRendererBuffer: () => ipcRenderer.invoke("renderer:replay-buffer"),
  // Memory Store
  memoryReadUser: () => ipcRenderer.invoke("memory:read-user"),
  memoryWriteUser: (content: any) => ipcRenderer.invoke("memory:write-user", content),
  memoryAppendUser: (content: any) => ipcRenderer.invoke("memory:append-user", content),
  memoryReadProject: () => ipcRenderer.invoke("memory:read-project"),
  memoryWriteProject: (content: any) => ipcRenderer.invoke("memory:write-project", content),
  memoryAppendProject: (content: any) => ipcRenderer.invoke("memory:append-project", content),
  memorySearch: (query: any) => ipcRenderer.invoke("memory:search", query),
  editMessage: (messageId: any, newContent: any) => ipcRenderer.invoke("session:edit-message", messageId, newContent),
  exportSessionMarkdown: (id: any) => ipcRenderer.invoke("session:export-markdown", id),
  // Skills
  skillsListAll: () => ipcRenderer.invoke("skills:list-all"),
  skillsLoadOne: (name: any) => ipcRenderer.invoke("skills:load-one", name),
  skillsReadContent: (filePath: any) => ipcRenderer.invoke("skills:read-content", filePath),
  skillsSetStatus: (name: any, status: any) => ipcRenderer.invoke("skills:set-status", name, status),
  skillsDelete: (name: any) => ipcRenderer.invoke("skills:delete", name),
  skillsDetectPatterns: () => ipcRenderer.invoke("skills:detect-patterns"),
  skillsCuratorRun: () => ipcRenderer.invoke("skills:curator-run"),
  skillsCuratorStatus: () => ipcRenderer.invoke("skills:curator-status"),
  skillsCuratorConfig: (config: any) => ipcRenderer.invoke("skills:curator-config", config),
  skillsHealth: (name: any) => ipcRenderer.invoke("skills:health", name),
  skillsSaveSkill: (name: any, meta: any, body: any) => ipcRenderer.invoke("skills:save", name, meta, body),
  skillsSearch: (query: any, limit: any) => ipcRenderer.invoke("skills:search", query, limit),
  skillsReindex: () => ipcRenderer.invoke("skills:reindex"),
  skillsAutoGenerate: (phrase: any, apiConfig: any) => ipcRenderer.invoke("skills:auto-generate", { phrase, apiConfig }),
  skillsAutoGenerateAll: (apiConfig: any) => ipcRenderer.invoke("skills:auto-generate-all", { apiConfig }),
  skillsTranslationsGet: () => ipcRenderer.invoke("skills:translations-get"),
  skillsTranslationsMissing: () => ipcRenderer.invoke("skills:translations-missing"),
  skillsTranslationsEnsure: (apiConfig: any) => ipcRenderer.invoke("skills:translations-ensure", apiConfig),
  skillsTranslationSet: (name: any, zh: any) => ipcRenderer.invoke("skills:translation-set", name, zh),
  onTranslationsUpdated: (cb: any) => ipcRenderer.on("skills:translations-updated", (_event, d) => cb(d)),
  listSkills: () => ipcRenderer.invoke("skills:list"),
  loadSkill: (name: any) => ipcRenderer.invoke("skills:load", name),
  onStreamStart: (cb: any) => ipcRenderer.on("stream:start", () => cb()),
  onOpencodeModels: (cb: any) => ipcRenderer.on("opencode:ready", (_event, d) => cb(d)),
  onStreamMetrics: (cb: any) => ipcRenderer.on("stream:metrics", (_event, d) => cb(d)),
  onStreamChunk: (cb: any) => ipcRenderer.on("stream:chunk", (_event, d) => cb(d)),
  onStreamReasoning: (cb: any) => ipcRenderer.on("stream:reasoning", (_event, d) => cb(d)),
  onStreamDone: (cb: any) => ipcRenderer.on("stream:done", () => cb()),
  onStreamError: (cb: any) => ipcRenderer.on("stream:error", (_event, d) => cb(d)),
  onStreamRetrying: (cb: any) => ipcRenderer.on("stream:retrying", (_event, d) => cb(d)),
  onStreamReset: (cb: any) => ipcRenderer.on("stream:reset", (_event, d) => cb(d)),
  onToolStart: (cb: any) => ipcRenderer.on("tool:start", (_event, d) => cb(d)),
  onToolResult: (cb: any) => ipcRenderer.on("tool:result", (_event, d) => cb(d)),
  onSubagentStart: (cb: any) => ipcRenderer.on("subagent:start", (_event, d) => cb(d)),
  onSubagentChunk: (cb: any) => ipcRenderer.on("subagent:chunk", (_event, d) => cb(d)),
  onSubagentProgress: (cb: any) => ipcRenderer.on("subagent:progress", (_event, d) => cb(d)),
  onSubagentDone: (cb: any) => ipcRenderer.on("subagent:done", (_event, d) => cb(d)),
  onSessionUpdate: (cb: any) => ipcRenderer.on("session:update", (_event, d) => cb(d)),
  onL0Budget: (cb: any) => ipcRenderer.on("l0:budget", (_event, d) => cb(d)),
  onContextUsage: (cb: any) => ipcRenderer.on("context:usage", (_event, d) => cb(d)),
  onTaskClear: (cb: any) => ipcRenderer.on("task:clear", () => cb()),
  onPatternsDetected: (cb: any) => ipcRenderer.on("agent-skill:patterns-detected", (_event, d) => cb(d)),
  // System prompt profiles
  listPromptProfiles: () => ipcRenderer.invoke("prompt:list"),
  getDefaultPrompt: () => ipcRenderer.invoke("prompt:default"),
  savePromptProfile: (profile: any) => ipcRenderer.invoke("prompt:save", profile),
  deletePromptProfile: (profileId: any) => ipcRenderer.invoke("prompt:delete", profileId),
  activatePromptProfile: (profileId: any) => ipcRenderer.invoke("prompt:activate", profileId),
  // MCP
  mcpList: () => ipcRenderer.invoke("mcp:list"),
  mcpConfig: () => ipcRenderer.invoke("mcp:config"),
  mcpAdd: (name: any, config: any) => ipcRenderer.invoke("mcp:add", { name, config }),
  mcpRemove: (name: any) => ipcRenderer.invoke("mcp:remove", name),
  mcpRestart: (name: any) => ipcRenderer.invoke("mcp:restart", name),
  mcpDetectLocal: () => ipcRenderer.invoke("mcp:detect-local"),
  mcpAddRemote: (name: any, url: any, headers: any) => ipcRenderer.invoke("mcp:add-remote", { name, url, headers }),
  mcpSaveAll: () => ipcRenderer.invoke("mcp:save-all"),
  mcpQuickAddSearxng: (url: any) => ipcRenderer.invoke("mcp:quick-add-searxng", url),
  mcpBuiltins: () => ipcRenderer.invoke("mcp:builtins"),
  mcpToggleBuiltin: (name: any, enabled: any) => ipcRenderer.invoke("mcp:toggle-builtin", { name, enabled }),
  sessionInfoUpdate: (snapshot: any) => ipcRenderer.send("session-info:update", snapshot),
  downloadMarkdown: (content: any) => ipcRenderer.invoke("dialog:download-markdown", content),
  // WeChat iLink Bridge
  wechatGetQrcode: () => ipcRenderer.invoke("wechat:get-qrcode"),
  wechatPollStatus: (qrcodeId: any) => ipcRenderer.invoke("wechat:poll-status", qrcodeId),
  wechatLogin: (creds: any) => ipcRenderer.invoke("wechat:login", creds),
  wechatLogout: () => ipcRenderer.invoke("wechat:logout"),
  wechatGetStatus: () => ipcRenderer.invoke("wechat:get-status"),
  onWechatBotStatus: (cb: any) => ipcRenderer.on("wechat:bot-status", (_e, d) => cb(d)),
  onWechatIncoming: (cb: any) => ipcRenderer.on("wechat:incoming", (_e, d) => cb(d)),
  syncApiToWechat: (cfg: any) => ipcRenderer.invoke("api:sync-to-wechat", cfg),
  // AskUserQuestion
  onAskQuestion: (cb: any) => ipcRenderer.on("ask:question", (_e, d) => cb(d)),
  respondQuestion: (id: any, answers: any) => ipcRenderer.invoke("ask:respond", { id, answers }),
  // Memory (multi-file)
  memoryListAll: () => ipcRenderer.invoke("memory:list-all"),
  memoryReadOne: (filename: any) => ipcRenderer.invoke("memory:read-one", filename),
  memoryCreate: (name: any, description: any, type: any, content: any) => ipcRenderer.invoke("memory:create", { name, description, type, content }),
  memoryUpdate: (filename: any, content: any, name: any, description: any, type: any) => ipcRenderer.invoke("memory:update", { filename, content, name, description, type }),
  memoryDelete: (filename: any) => ipcRenderer.invoke("memory:delete", filename),
  memoryPurgeByType: (type: any) => ipcRenderer.invoke("memory:purge-by-type", type),
  // Prompts (user-defined reusable prompts — Stage 2)
  promptsList: () => ipcRenderer.invoke("prompts:list"),
  promptsRead: (id: any) => ipcRenderer.invoke("prompts:read", id),
  promptsCreate: (input: any) => ipcRenderer.invoke("prompts:create", input),
  promptsUpdate: (id: any, input: any) => ipcRenderer.invoke("prompts:update", id, input),
  promptsDelete: (id: any) => ipcRenderer.invoke("prompts:delete", id),
  workspaceGet: () => ipcRenderer.invoke("workspace:get"),
  workspaceSet: (path: any) => ipcRenderer.invoke("workspace:set", path),
  workspacePick: () => ipcRenderer.invoke("workspace:pick"),
  workspaceNeedsFirstPick: () => ipcRenderer.invoke("workspace:needs-first-pick"),
  // Knowledge Base
  kbGetVault: () => ipcRenderer.invoke("kb:get-vault"),
  kbSetVault: (path: any) => ipcRenderer.invoke("kb:set-vault", path),
  kbPickVault: () => ipcRenderer.invoke("kb:pick-vault"),
  kbConfig: () => ipcRenderer.invoke("kb:config"),
  kbSetConfig: (cfg: any) => ipcRenderer.invoke("kb:set-config", cfg),
  kbScan: () => ipcRenderer.invoke("kb:scan"),
  kbStatus: () => ipcRenderer.invoke("kb:status"),
  kbSearch: (query: any, limit: any) => ipcRenderer.invoke("kb:search", query, limit),
  kbList: (offset: any, limit: any) => ipcRenderer.invoke("kb:list", offset, limit),
  kbGetNote: (path: any) => ipcRenderer.invoke("kb:get-note", path),
  kbCreateNote: (path: any, content: any, tags: any) => ipcRenderer.invoke("kb:create-note", { path, content, tags }),
  kbUpdateNote: (path: any, content: any) => ipcRenderer.invoke("kb:update-note", { path, content }),
  kbDeleteNote: (path: any) => ipcRenderer.invoke("kb:delete-note", path),
  kbOllamaModels: () => ipcRenderer.invoke("kb:ollama-models"),

  // Update Manager
  updateCheckVersion: () => ipcRenderer.invoke("update:get-version"),
  updateCheckForUpdates: () => ipcRenderer.invoke("update:check"),
  updateDownload: () => ipcRenderer.invoke("update:download"),
  updateSkip: (version: any) => ipcRenderer.invoke("update:skip", version),
  updateInstall: () => ipcRenderer.invoke("update:install"),
  onUpdateStatus: (cb: any) => ipcRenderer.on("update:status", (_e, d) => cb(d)),
  onUpdateProgress: (cb: any) => ipcRenderer.on("update:progress", (_e, d) => cb(d)),

  // Encrypted API Key Storage
  saveApiKey: (provider: any, key: any) => ipcRenderer.invoke("api-key:save", { provider, key }),
  loadApiKey: (provider: any) => ipcRenderer.invoke("api-key:load", { provider }),
  deleteApiKey: (provider: any) => ipcRenderer.invoke("api-key:delete", { provider }),
  getEnvVar: (name: any) => ipcRenderer.invoke("env:get", name),
});
